services:
  pgdb:
    build:
      context: ./pgdb
      dockerfile: Dockerfile
    image: "${HOST_SEGUE2_USER:-main}-segue2-pgsql16"
    container_name: segue2-pgsql16
    restart: unless-stopped
    env_file:
      - ./var/pgdb.env
    networks:
      - segue2
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_INITDB_ARGS=--auth-host=md5 --auth-local=md5
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - ${HOST_POSTGRES_DATA:-./appdata/pgdb/data}:/var/lib/postgresql/data
      - ./pgdb/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pgdb/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  plex:
    build:
      context: ./tp-app-plex
      dockerfile: Dockerfile
    # Alternative: use the official image directly
    # image: plexinc/pms-docker:latest
    container_name: segue2-plex
    restart: unless-stopped
    networks:
      - segue2
    hostname: "${HOST_SEGUE2_USER:-main}-segue2-plex"
    env_file:
      - ./var/plex.env
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM:-""}
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=Europe/Amsterdam
      - HOST_SEGUE2_USER=${HOST_SEGUE2_USER:-main}
    volumes:
      - ${HOST_USER_DATA:-./appdata/plex}/config:/config
      - ${HOST_USER_DATA:-./appdata/plex}/transcode:/transcode
      - ${HOST_MEDIA_PATH:-./appdata/plex/media}:/media:ro  # Replace with your media directory
      - /dev/shm:/dev/shm  # For transcoding performance
    # Uncomment the devices section below if you have hardware transcoding available
    # devices:
    #   - /dev/dri:/dev/dri  # For hardware transcoding (if available)
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    # The Plex Media Server starts automatically - it's the default CMD in the base image
    # If you need to override, uncomment the next line:
    # command: ["/init"]
# Optional: Create an entry PLEX_CLAIM=claim-xxxxxxxxxxxxxxxxx as variable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/web"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  segue2:
    name: segue2
    driver: bridge
    ipam:
      config:
        - subnet: ${SEGUE2_NETWORK:-192.168.171.0/24}
