#!/bin/bash
echo "=== Plex Diagnostic Information ==="
echo "Date: $(date)"
echo "User: $(whoami)"
echo "UID: $(id -u), GID: $(id -g)"
echo ""
echo "=== Environment Variables ==="
echo "PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR: $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR"
echo "PLEX_MEDIA_SERVER_HOME: $PLEX_MEDIA_SERVER_HOME"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo "PLEX_CLAIM: ${PLEX_CLAIM:+SET}"
echo ""
echo "=== Directory Permissions ==="
ls -la /config 2>/dev/null || echo "/config directory does not exist"
ls -la /tv 2>/dev/null || echo "/tv directory does not exist"
ls -la /movies 2>/dev/null || echo "/movies directory does not exist"
echo ""
echo "=== Plex Binary Information ==="
ls -la "${PLEX_MEDIA_SERVER_HOME}/Plex Media Server" 2>/dev/null || echo "Plex binary not found"
echo ""
echo "=== Running Processes ==="
ps aux | grep -i plex | grep -v grep
echo ""
echo "=== Device Information ==="
ls -la /dev/dri/ 2>/dev/null || echo "No DRI devices found"
echo ""
echo "=== Log Files ==="
find /config -name "*.log" -type f 2>/dev/null | head -5
echo "=== End Diagnostic ==="
